name: Automated Data Update

on:
  # schedule:
  #   # Run every 5 minutes (adjust as needed)
  #   - cron: '*/5 * * * *'
  workflow_dispatch: # Allow manual triggering only

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Create topics config for Node.js
        run: |
          # Convert TypeScript topics config to JSON for Node.js scripts
          node -e "
          import('./src/config/topics.ts').then(module => {
            const fs = require('fs');
            fs.writeFileSync('./src/config/topics.json', JSON.stringify(module.default || module.topics, null, 2));
          }).catch(err => console.log('No topics.ts found, will use defaults'));
          " || echo "Using default topics"

      - name: Run sentiment data ingestion
        env:
          # Add your API credentials as GitHub secrets
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          UPDATE_INTERVAL: 5
        run: npm run ingest

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code public/data/ || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/data/
          git commit -m "Auto-update sentiment data - $(date)"
          git push

      - name: Trigger deployment
        if: steps.git-check.outputs.changes == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'deploy.yml'
            });

